name: Deploy to Kubernetes

on:
 
  push:
    branches: 
    - master
    - isshy35/ismail
    - develop
    
#jobs
jobs:
  BuildImage:
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 670412359701.dkr.ecr.eu-north-1.amazonaws.com   ##${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tcoc-frontend
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
      
  Deployment:
   needs: BuildImage
   runs-on: ubuntu-latest
   steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update Image in Kubernetes Manifest
        run: sed -i "s#SAMPLE#670412359701.dkr.ecr.eu-north-1.amazonaws.com/tcoc-frontend:${{ github.run_number }}#g" manifests/deployment.yml    
      - name: Install AWS CLI
        run: |
         sudo apt-get update
         sudo apt-get install -y awscli
         aws --version
      - name: Configure AWS credentials
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
         aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
         aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
         aws configure set region eu-north-1
      - name: Update Kubeconfig
        run: |
         aws eks update-kubeconfig --name TCOC-CLUSTER --region eu-north-1
      - name: Apply changes 
        run: kubectl apply -f manifests/deployment.yml
